budget/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import DetailView

from .models.recette import Recette
from .models.depense import Depense
from .views import dashboard, recette, depense, origine, parametre, moyenspaiement, categorie, camp

urlpatterns = [
    path('', dashboard.index, name='dashboard'),

    path('recettes', recette.recette_list, name='recettes'),
    path('recettes/create', recette.CreateRecette.as_view(), name='create_recette'),
    path('recettes/update/<int:pk>', recette.UpdateRecette.as_view(), name='update_recette'),
    path('recettes/delete/<int:pk>', recette.DeleteRecette.as_view(), name='delete_recette'),
    path('recettes/<int:pk>', login_required(DetailView.as_view(model=Recette,
                                                                template_name='budget/recette/recette_detail.html')),
         name='detail_recette'),

    path('depenses', depense.depense_list, name='depenses'),
    path('depenses/create', depense.CreateDepense.as_view(), name='create_depense'),
    path('depenses/update/<int:pk>', depense.UpdateDepense.as_view(), name='update_depense'),
    path('depenses/delete/<int:pk>', depense.DeleteDepense.as_view(), name='delete_depense'),
    path('depenses/<int:pk>', login_required(DetailView.as_view(model=Depense,
                                                                template_name='budget/depense/depense_detail.html')),
         name='detail_depense'),

    path('settings/', parametre.settings, name='settings'),

    path('settings/origine/create', origine.CreateOrigine.as_view(), name='create_origine'),
    path('settings/origine/delete/<int:pk>', origine.DeleteOrigine.as_view(), name='delete_origine'),

    path('settings/moyenpaiement/create', moyenspaiement.CreateMoyensPaiement.as_view(), name='create_moyenpaiement'),
    path('settings/moyenpaiement/delete/<int:pk>', moyenspaiement.DeleteMoyensPaiement.as_view(),
         name='delete_moyenpaiement'),

    path('settings/categorie/update/<int:pk>', categorie.UpdateCategories.as_view(), name='update_categorie'),
    path('settings/categorie/create', categorie.CreateCategories.as_view(), name='create_categorie'),
    path('settings/categorie/delete/<int:pk>', categorie.DeleteCategories.as_view(), name='delete_categorie'),

    path('settings/camp/update/<int:pk>', camp.UpdateCamp.as_view(), name='update_camp'),
    path('settings/camp/create', camp.CreateCamp.as_view(), name='create_camp'),
]

dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('budget.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

budget/models/parametre.py
from django.db import models


class MoyensPaiement(models.Model):
    moyens = models.CharField(verbose_name="Moyens de paiements", null=True, blank=True, max_length=40)

    def __str__(self):
        return self.moyens


class Origine(models.Model):
    origine = models.CharField(verbose_name="Origine", null=True, blank=True, max_length=40)

    def __str__(self):
        return self.origine


class Categorie(models.Model):
    categorie = models.CharField(verbose_name="Catégorie", null=True, blank=True, max_length=40)
    montant_previsionnel = models.FloatField(verbose_name="montant prévisionnel", default=0)

    def __str__(self):
        return self.categorie


class Camp(models.Model):
    date_debut = models.DateField(verbose_name="Date de debut du camp")
    date_fin = models.DateField(verbose_name="Date de fin du camp")

    def __str__(self):
        return str(self.date_debut) + " " + str(self.date_fin)

budget/forms/camp.py
from django.forms import ModelForm

from budget.models.parametre import Camp


class CampBaseForm:
    def clean(self):
        clean_data = ModelForm.clean(self)

        def verifier_element(name):
            if not clean_data.get(name):
                msg = f"{name} doit être spécifié"
                self._errors[name] = self.error_class([msg])
                del clean_data[name]


        verifier_element('date_debut')
        verifier_element('date_fin')

        return clean_data


class CampForm(CampBaseForm, ModelForm):
    class Meta:
        model = Camp
        fields = ('date_debut', 'date_fin')

budget/views/camp.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from budget.forms.camp import CampForm
from budget.models.parametre import Camp


@method_decorator(login_required(), name='dispatch')
@method_decorator(permission_required('budget.add_camp', raise_exception=True), name='dispatch')
class CreateCamp(CreateView, LoginRequiredMixin):
    model = Camp
    form_class = CampForm
    template_name = 'budget/settings/camp/camp_form.html'

    def get_success_url(self):
        return reverse_lazy('settings')


@method_decorator(login_required(), name='dispatch')
@method_decorator(permission_required('budget.change_camp', raise_exception=True), name='dispatch')
class UpdateCamp(UpdateView, LoginRequiredMixin):
    model = Camp
    form_class = CampForm
    template_name = 'budget/settings/camp/camp_form.html'

    def get_success_url(self):
        return reverse_lazy('settings')

templates/budget/settings/camp/camp_form.html
{% extends 'budget/base.html' %}
{% load crispy_forms_filters %}

{% block title %}Dashboard - Paramètre{% endblock %}

{% block content %}
    <div style="background: linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(239,239,239,1) 50%);">
        <div class="container">
            <h3>Dates du camp</h3>

            <form method="post" enctype="multipart/form-data" action="">
                {% csrf_token %}
                {{ form|crispy }}

                <div class="row px-2 py-2">
                    <div class="col">
                        <a href="{% url 'settings' %}" class="btn btn-secondary">Annuler</a>
                    </div>
                    <div class="col text-right">
                        <input class="btn btn-info" type="submit" />
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block script %}

<!-- XDSoft DateTimePicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
  <script>
$(function () {
      $("#id_date_debut").datetimepicker( {
          format:'Y-m-d',
          dateFormat: 'Y-m-d',
      });
      $("#id_date_fin").datetimepicker( {
          format:'Y-m-d',
          dateFormat: 'Y-m-d',
      });
    });
  </script>
{% endblock %}